# Generated by Django 5.0.6 on 2024-06-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_item_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='note',
        ),
    ]
