# Generated by Django 5.0.6 on 2024-06-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
